## Exercice : Distance matrix
Compute a 2 dimensional distance array

In [14]:
import numpy as np
dist_to_origin = [0, 1498, 1063, 1968, 1498, 1758, 1469, 1472, 2230, 2391]
len_dist_to_rigin = len(dist_to_origin)


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [27]:
def dist(X1,X2):
    return abs(X2-X1) #Too lazy to express the distance with 2 coordinate

dist(0,1498)

1498

In [19]:
dist_matrix = np.zeros((len_dist_to_rigin, len_dist_to_rigin))
dist_matrix

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [26]:
for i in range(len_dist_to_rigin): 
    for j in range(len_dist_to_rigin):
        val = dist(dist_to_origin[i],dist_to_origin[j])
        dist_matrix[i][j] = val
dist_matrix

array([[   0., 1498., 1063., 1968., 1498., 1758., 1469., 1472., 2230.,
        2391.],
       [1498.,    0.,  435.,  470.,    0.,  260.,   29.,   26.,  732.,
         893.],
       [1063.,  435.,    0.,  905.,  435.,  695.,  406.,  409., 1167.,
        1328.],
       [1968.,  470.,  905.,    0.,  470.,  210.,  499.,  496.,  262.,
         423.],
       [1498.,    0.,  435.,  470.,    0.,  260.,   29.,   26.,  732.,
         893.],
       [1758.,  260.,  695.,  210.,  260.,    0.,  289.,  286.,  472.,
         633.],
       [1469.,   29.,  406.,  499.,   29.,  289.,    0.,    3.,  761.,
         922.],
       [1472.,   26.,  409.,  496.,   26.,  286.,    3.,    0.,  758.,
         919.],
       [2230.,  732., 1167.,  262.,  732.,  472.,  761.,  758.,    0.,
         161.],
       [2391.,  893., 1328.,  423.,  893.,  633.,  922.,  919.,  161.,
           0.]])

### Correction :

In [28]:
dist = np.array(dist_to_origin)
dist

array([   0, 1498, 1063, 1968, 1498, 1758, 1469, 1472, 2230, 2391])

In [30]:
dist_T = dist.reshape(10, 1)
dist_matrix = np.abs(dist - dist_T) #Better and faster
dist_matrix 


array([[   0, 1498, 1063, 1968, 1498, 1758, 1469, 1472, 2230, 2391],
       [1498,    0,  435,  470,    0,  260,   29,   26,  732,  893],
       [1063,  435,    0,  905,  435,  695,  406,  409, 1167, 1328],
       [1968,  470,  905,    0,  470,  210,  499,  496,  262,  423],
       [1498,    0,  435,  470,    0,  260,   29,   26,  732,  893],
       [1758,  260,  695,  210,  260,    0,  289,  286,  472,  633],
       [1469,   29,  406,  499,   29,  289,    0,    3,  761,  922],
       [1472,   26,  409,  496,   26,  286,    3,    0,  758,  919],
       [2230,  732, 1167,  262,  732,  472,  761,  758,    0,  161],
       [2391,  893, 1328,  423,  893,  633,  922,  919,  161,    0]])

## Copies and views 

We conclude this short introduction to NumPy with a very important concept. When performing operations with arrays, sometimes the data is copied into a new array, and sometimes the modifications are made on the original array.

### Name binding

First of all, when we make an assignment, it is important to recall that in Python, this doesn’t create a new object, but instead it assigns two names to the same object.

In [31]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [32]:
b = a  # "a" and "b" are bound to the same array
b[0] = 5
a

array([5, 1, 2, 3, 4])

### Views vs. copies
Another important point to keep in mind is that slicing an array in NumPy returns a view and not a separate copy of it.

In [35]:
a = np.arange(10)
b = a[:2]  # "b" is a narrower view of the array
b


array([0, 1])

In [34]:
b[0] = 10
a

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [36]:
a = np.arange(10)
b = a.copy()[:2]  # "b" is bound to a new copy of the array
b[0] = 10
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Reshaping
The difference between a view and a copy can be a bit subtle. For instance, the reshape() function returns a view of the array, but with a new shape.

In [37]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [38]:
b = a.reshape(3, 4)  # reshape() returns a view of the array, but with a new shape
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [39]:
b[0] = 10  # changes the underlying data of both "a" and "b"
a

array([10, 10, 10, 10,  4,  5,  6,  7,  8,  9, 10, 11])

In [40]:
b

array([[10, 10, 10, 10],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])